{% set name = "ensaio" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ensaio-{{ version }}.tar.gz
  sha256: 5a2da344b5bfe99ffaaa4f418526daeb1e0f3055e2b527696eba6e4ccb30ec23

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - pooch >=1.5.0,<2.0.0

test:
  imports:
    - ensaio
    - ensaio.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fatiando/ensaio
  summary: Practice datasets to probe your code
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
