{% set name = "ensaio" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ensaio-{{ version }}.tar.gz
  sha256: 8c22bcabae92fbb86851b31c2c64280f27a9ae34c839c4f2cd75c5ef39739560

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pooch >=1.5.0,<2.0.0

test:
  imports:
    - ensaio
    - ensaio.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fatiando/ensaio
  summary: Practice datasets to probe your code
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
