{% set name = "ensaio" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ensaio-{{ version }}.tar.gz
  sha256: 29085eb60e28b17f151f833207cc87c59a39e863ed4c074dbb760e405fa43404

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pooch >=1.5.0,<2.0.0

test:
  imports:
    - ensaio
    - ensaio.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fatiando/ensaio
  summary: Practice datasets to probe your code
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - leouieda
